version: 2
updates:
- package-ecosystem: gomod
  directory: "/"
  schedule:
    interval: daily
  target-branch: v1
- package-ecosystem: gomod
  directory: "/"
  schedule:
    interval: daily
  target-branch: main
