version: 2.1

orbs:
  codecov: codecov/codecov@1.2

executors:
  node:
    docker:
      - image: node:16-slim
  golangci-lint:
    docker:
      - image: golangci/golangci-lint:v1.41-alpine
  golang:
    docker:
      - image: golang:1.16

jobs:
  lint-markdown:
    executor: node
    steps:
      - checkout
      - run:
          name: Install markdownlint
          command: npm install -g markdownlint-cli
      - run:
          name: Check for Lint
          command: markdownlint .

  lint-source:
    executor: golangci-lint
    steps:
      - checkout
      - run:
          name: Check for Lint
          command: golangci-lint run

  check-go-mod:
    executor: golang
    steps:
      - checkout
      - run:
          name: Go Mod Tidy
          command: go mod tidy
      - run:
          name: Check Module Tidiness
          command: git diff --exit-code -- go.mod go.sum

  build-source:
    executor: golang
    steps:
      - checkout
      - run:
          name: Build Source
          command: go run mage.go build:source

  unit-test:
    executor: golang
    steps:
      - checkout
      - run:
          name: Run Unit Tests
          command: go run mage.go cover:unit cover.out
      - codecov/upload:
          file: cover.out

workflows:
  version: 2

  build_and_test:
    jobs:
      - lint-markdown
      - lint-source
      - check-go-mod
      - build-source
      - unit-test
